version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: AdvertisingPlatforms.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
